/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: ["class"],
  content: [
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/**/*.{js,ts,jsx,tsx,mdx}",
    "*.{js,ts,jsx,tsx,mdx}",
  ],
  prefix: "",
  theme: {
    container: {
      center: true,
      padding: "2rem",
      screens: {
        "2xl": "1400px",
      },
    },
    extend: {
      screens: {
        xs: '480px',
        sm: '640px',
        md: '768px',
        lg: '1024px',
        xl: '1280px',
        '2xl': '1536px',
      },
      fontFamily: {
        serif: ["Times New Roman", "Georgia", "Garamond", "serif"],
      },
      colors: {
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        primary: {
          DEFAULT: "hsl(var(--primary))",
          foreground: "hsl(var(--primary-foreground))",
        },
        secondary: {
          DEFAULT: "hsl(var(--secondary))",
          foreground: "hsl(var(--secondary-foreground))",
        },
        destructive: {
          DEFAULT: "hsl(var(--destructive))",
          foreground: "hsl(var(--destructive-foreground))",
        },
        muted: {
          DEFAULT: "hsl(var(--muted))",
          foreground: "hsl(var(--muted-foreground))",
        },
        accent: {
          DEFAULT: "hsl(var(--accent))",
          foreground: "hsl(var(--accent-foreground))",
        },
        popover: {
          DEFAULT: "hsl(var(--popover))",
          foreground: "hsl(var(--popover-foreground))",
        },
        card: {
          DEFAULT: "hsl(var(--card))",
          foreground: "hsl(var(--card-foreground))",
        },
      },
      borderRadius: {
        lg: "var(--radius)",
        md: "calc(var(--radius) - 2px)",
        sm: "calc(var(--radius) - 4px)",
      },
      keyframes: {
        "accordion-down": {
          from: { height: "0" },
          to: { height: "var(--radix-accordion-content-height)" },
        },
        "accordion-up": {
          from: { height: "var(--radix-accordion-content-height)" },
          to: { height: "0" },
        },
      },
      animation: {
        "accordion-down": "accordion-down 0.2s ease-out",
        "accordion-up": "accordion-up 0.2s ease-out",
      },
    },
  },
  plugins: [],
  // Force include all classes
  safelist: [
    "bg-black",
    "text-black",
    "border-black",
    "border-2",
    "border-4",
    "border-b-2",
    "border-b-4",
    "border-t-2",
    "border-t-4",
    "grid",
    "grid-cols-1",
    "lg:grid-cols-12",
    "lg:col-span-3",
    "lg:col-span-6",
    "md:grid-cols-2",
    "flex",
    "justify-between",
    "justify-center",
    "items-center",
    "text-center",
    "text-right",
    "text-justify",
    "space-y-6",
    "space-y-3",
    "space-y-2",
    "space-y-1",
    "space-x-4",
    "space-x-2",
    "p-4",
    "p-8",
    "mb-2",
    "mb-3",
    "mb-4",
    "mb-6",
    "mt-8",
    "pt-4",
    "pb-4",
    "pb-2",
    "text-xs",
    "text-sm",
    "text-base",
    "text-lg",
    "text-xl",
    "text-2xl",
    "text-3xl",
    "text-4xl",
    "text-5xl",
    "text-6xl",
    "text-7xl",
    "text-8xl",
    "font-bold",
    "font-black",
    "font-light",
    "italic",
    "uppercase",
    "tracking-wide",
    "tracking-wider",
    "leading-tight",
    "leading-relaxed",
    "leading-none",
    "float-left",
    "hover:underline",
    "max-w-7xl",
    "max-w-4xl",
    "mx-auto",
    "min-h-screen",
    "gap-6",
    "rounded-full",
    "overflow-hidden",
    "object-cover",
    "grayscale",
    "w-full",
    "h-full",
    "w-24",
    "h-24",
    "font-serif",
  ],
}
